apiVersion: v1
kind: Service
metadata:
  name: hanami-tls-service
  labels:
    run: hanami
spec:
  selector:
    app: hanami
  ports:
    - name: input
      protocol: TCP
      port: 8443
      targetPort: 8443
  type: ClusterIP
