[workspace]
members = [
    "src/binaries/sakura",
    "src/binaries/hanami",
    "src/binaries/miko", 
    "src/binaries/ryokan", 
    "src/binaries/torii", 
    "src/binaries/omamori", 
    "src/binaries/onsen", 
    "src/libs/rust/ainari_common",
    "src/libs/rust/ainari_dataset", 
    "src/libs/rust/ainari_api", 
    "src/libs/rust/ainari_hardware", 
    "src/libs/rust/ainari_clients", 
    "src/libs/rust/ainari_api_structs"
]

[profile.dev]
opt-level = 0
debug = true
overflow-checks = true

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 8
strip = true
