---
- name: Create base-directory
  become: true
  file:
    path: /etc/openhanami
    state: directory
    mode: "0777"

- name: Create checkpoint-directory
  file:
    path: "{{ hanami_checkpoint_location }}"
    state: directory
    mode: "0777"

- name: Create dataset-directory
  file:
    path: "{{ hanami_dataset_location }}"
    state: directory
    mode: "0777"


- name: Create log-directory
  become: true
  file:
    path: "{{ hanami_log_dir }}"
    state: directory
    mode: "0777"


- name: Copy policies
  copy:
    src: policies
    dest: /etc/openhanami/policies
    mode: "0777"

- name: Create hanami-config from template
  template:
    src: hanami.conf.j2
    dest: /etc/openhanami/hanami.conf
    mode: "0777"

- name: Create a token-file
  copy:
    dest: "{{ hanami_token_key_path }}"
    content: "{{ lookup('env', 'TOKEN_KEY') }}"
    mode: "0600"


- name: Create hanami docker-container
  become: true
  community.docker.docker_container:
    name: hanami
    image: kitsudaiki/hanami:{{ hanami_docker_tag }}
    state: started
    pull: true
    detach: true
    command: "hanami"
    env:
      HANAMI_ADMIN_USER_ID: "{{ lookup('env', 'ADMIN_USER_ID') }}"
      HANAMI_ADMIN_USER_NAME: "{{ lookup('env', 'ADMIN_USER_NAME') }}"
      HANAMI_ADMIN_PASSPHRASE: "{{ lookup('env', 'ADMIN_PASSPHRASE') }}"
    ports:
      - "11418:11418"
    mounts:
      - source: /etc/openhanami
        target: /etc/openhanami
        type: bind
        read_only: false
      - source: "{{ hanami_log_dir }}"
        target: "{{ hanami_log_dir }}"
        type: bind
        read_only: false
