---
- name: Install nginx
  become: true
  ansible.builtin.apt:
    name: ['nginx']
    state: present
    update_cache: true


- name: Create nginx-config from template
  become: true
  template:
    src: hanami_nginx.conf.j2
    dest: /etc/nginx/sites-enabled/hanami.conf
    mode: "0777"


- name: Create private key for self-signed certificate
  community.crypto.openssl_privatekey:
    path: "{{ hanami_ssl_key_path }}"
    type: RSA

- name: Create simple self-signed certificate
  community.crypto.x509_certificate:
    path: "{{ hanami_ssl_cert_path }}"
    privatekey_path: "{{ hanami_ssl_key_path }}"
    provider: selfsigned


- name: Restart nginx to apply config
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
