ADMIN_USER_ID = ENV['ADMIN_USER_ID']
ADMIN_USER_NAME = ENV['ADMIN_USER_NAME']
ADMIN_PASSPHRASE = ENV['ADMIN_PASSPHRASE']
TOKEN_KEY = ENV['TOKEN_KEY']

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vbox|
    vbox.name = "openhanami-test"
    vbox.memory = 4096
    vbox.cpus = 4
  end
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "openhanami-test"
  config.vm.network "private_network", type: "dhcp"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "openhanami-playbook/deploy.yml"
    # ansible.verbose = "v"
    ansible.extra_vars = {
      env: ADMIN_USER_ID,
      env: ADMIN_USER_NAME,
      env: ADMIN_PASSPHRASE,
      env: TOKEN_KEY,
    }
    # ansible.inventory_path = "inventory"
  end
end

