apiVersion: v1
kind: PersistentVolume
metadata:
  name: hanami-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hanami-sc
  hostPath:
    path: /etc/hanami_data/
