// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: azuki_messages.proto3

#include "azuki_messages.proto3.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
class SetCpuSpeed_MessageDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SetCpuSpeed_Message> _instance;
} _SetCpuSpeed_Message_default_instance_;
static void InitDefaultsscc_info_SetCpuSpeed_Message_azuki_5fmessages_2eproto3() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_SetCpuSpeed_Message_default_instance_;
    new (ptr) ::SetCpuSpeed_Message();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::SetCpuSpeed_Message::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SetCpuSpeed_Message_azuki_5fmessages_2eproto3 =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SetCpuSpeed_Message_azuki_5fmessages_2eproto3}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_azuki_5fmessages_2eproto3[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_azuki_5fmessages_2eproto3[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_azuki_5fmessages_2eproto3 = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_azuki_5fmessages_2eproto3::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::SetCpuSpeed_Message, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::SetCpuSpeed_Message, type_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::SetCpuSpeed_Message)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_SetCpuSpeed_Message_default_instance_),
};

const char descriptor_table_protodef_azuki_5fmessages_2eproto3[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025azuki_messages.proto3\"0\n\023SetCpuSpeed_M"
  "essage\022\031\n\004type\030\001 \001(\0162\013.SpeedState*G\n\nSpe"
  "edState\022\021\n\rMINIMUM_SPEED\020\000\022\023\n\017AUTOMATIC_"
  "SPEED\020\001\022\021\n\rMAXIMUM_SPEED\020\002b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_azuki_5fmessages_2eproto3_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_azuki_5fmessages_2eproto3_sccs[1] = {
  &scc_info_SetCpuSpeed_Message_azuki_5fmessages_2eproto3.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_azuki_5fmessages_2eproto3_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_azuki_5fmessages_2eproto3 = {
  false, false, descriptor_table_protodef_azuki_5fmessages_2eproto3, "azuki_messages.proto3", 154,
  &descriptor_table_azuki_5fmessages_2eproto3_once, descriptor_table_azuki_5fmessages_2eproto3_sccs, descriptor_table_azuki_5fmessages_2eproto3_deps, 1, 0,
  schemas, file_default_instances, TableStruct_azuki_5fmessages_2eproto3::offsets,
  file_level_metadata_azuki_5fmessages_2eproto3, 1, file_level_enum_descriptors_azuki_5fmessages_2eproto3, file_level_service_descriptors_azuki_5fmessages_2eproto3,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_azuki_5fmessages_2eproto3 = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_azuki_5fmessages_2eproto3)), true);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SpeedState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_azuki_5fmessages_2eproto3);
  return file_level_enum_descriptors_azuki_5fmessages_2eproto3[0];
}
bool SpeedState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void SetCpuSpeed_Message::InitAsDefaultInstance() {
}
class SetCpuSpeed_Message::_Internal {
 public:
};

SetCpuSpeed_Message::SetCpuSpeed_Message(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:SetCpuSpeed_Message)
}
SetCpuSpeed_Message::SetCpuSpeed_Message(const SetCpuSpeed_Message& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  type_ = from.type_;
  // @@protoc_insertion_point(copy_constructor:SetCpuSpeed_Message)
}

void SetCpuSpeed_Message::SharedCtor() {
  type_ = 0;
}

SetCpuSpeed_Message::~SetCpuSpeed_Message() {
  // @@protoc_insertion_point(destructor:SetCpuSpeed_Message)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SetCpuSpeed_Message::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void SetCpuSpeed_Message::ArenaDtor(void* object) {
  SetCpuSpeed_Message* _this = reinterpret_cast< SetCpuSpeed_Message* >(object);
  (void)_this;
}
void SetCpuSpeed_Message::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SetCpuSpeed_Message::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SetCpuSpeed_Message& SetCpuSpeed_Message::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SetCpuSpeed_Message_azuki_5fmessages_2eproto3.base);
  return *internal_default_instance();
}


void SetCpuSpeed_Message::Clear() {
// @@protoc_insertion_point(message_clear_start:SetCpuSpeed_Message)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  type_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SetCpuSpeed_Message::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .SpeedState type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::SpeedState>(val));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SetCpuSpeed_Message::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SetCpuSpeed_Message)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .SpeedState type = 1;
  if (this->type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SetCpuSpeed_Message)
  return target;
}

size_t SetCpuSpeed_Message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SetCpuSpeed_Message)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .SpeedState type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_type());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SetCpuSpeed_Message::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SetCpuSpeed_Message)
  GOOGLE_DCHECK_NE(&from, this);
  const SetCpuSpeed_Message* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SetCpuSpeed_Message>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SetCpuSpeed_Message)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SetCpuSpeed_Message)
    MergeFrom(*source);
  }
}

void SetCpuSpeed_Message::MergeFrom(const SetCpuSpeed_Message& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SetCpuSpeed_Message)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.type() != 0) {
    _internal_set_type(from._internal_type());
  }
}

void SetCpuSpeed_Message::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SetCpuSpeed_Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SetCpuSpeed_Message::CopyFrom(const SetCpuSpeed_Message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SetCpuSpeed_Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SetCpuSpeed_Message::IsInitialized() const {
  return true;
}

void SetCpuSpeed_Message::InternalSwap(SetCpuSpeed_Message* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(type_, other->type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SetCpuSpeed_Message::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::SetCpuSpeed_Message* Arena::CreateMaybeMessage< ::SetCpuSpeed_Message >(Arena* arena) {
  return Arena::CreateMessageInternal< ::SetCpuSpeed_Message >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
