from ubuntu:22.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y \
        cppcheck \
        clang-format-15 \
        python3 \
        python3-pip
RUN pip3 install \
        ansible-lint \
        flake8
