---
- name: Install required packages
  become: true
  ansible.builtin.apt:
    name: ['python3',
           'python3-pip',
           'python3-setuptools',
           'apt-transport-https',
           'ca-certificates',
           'curl',
           'software-properties-common',
           'virtualenv']
    state: present
    update_cache: true

- name: Add Docker GPG apt Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Update apt and install docker-ce
  become: true
  apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Install docker-py python package
  become: true
  ansible.builtin.pip:
    name: "docker"
